/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testString() {
        String a = "1";
        String b = "1";
        System.out.println(a == b);
        String d = "12";
        String c = a + "2";
        System.out.println(c == d);
    }
}
